// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbkkoxgeecdbmjmifihz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRia2tveGdlZWNkYm1qbWlmaWh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3OTU4MjUsImV4cCI6MjA5MDM3MTgyNX0.HfUiWsFgVVQpkugMhO18sETGDqaOuDsRyzm8VyTdw5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});